import { Poppins, Newsreader } from "next/font/google"; // add imports
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"], // light, regular, medium, bold
});

const newsreader = Newsreader({
  variable: "--font-newsreader",
  subsets: ["latin"],
  weight: ["300", "200", "400", "700", "500"], // adjust weights as needed
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${newsreader.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
